Repository CryptoKraken/crypto-kraken-services, pull requests merged in 2018-06, with the labels that each got.

#87 Replace get request to post request in the createOrder method of the KuCoinService
  src/services/kucoin/kucoin-service.ts
  tests/services/kucoin/kucoin-service.spec.ts
Labels: bug

#91 Iss90
  src/services/kucoin/kucoin-signature-maker.ts
  tests/services/kucoin/kucoin-signature-maker.spec.ts
Labels: bug

#92 Small improvements
  package-lock.json
  package.json
  src/index.ts
Labels: enhancement

#95 Add travis ci
  .travis.yml
  appveyor.yml
  package.json
Labels: enviroment

#99 Sort fields of the querystring object in the KuCoin signature maker alphabetically
  src/services/kucoin/kucoin-service.ts
  src/services/kucoin/kucoin-signature-maker.ts
  tests/services/kucoin/kucoin-signature-maker.spec.ts
Labels: bug

#106 Implement the Yobit createOrder method
  README.md
  packages/crypto-kraken-exchange-services/src/services/yobit/constants.ts
  packages/crypto-kraken-exchange-services/src/services/yobit/yobit-nonce-factory.ts
  packages/crypto-kraken-exchange-services/src/services/yobit/yobit-response-parser.ts
  packages/crypto-kraken-exchange-services/src/services/yobit/yobit-service.ts
  packages/crypto-kraken-exchange-services/src/services/yobit/yobit-utils.ts
  packages/crypto-kraken-exchange-services/tests/functional/yobit-service.spec.ts
  packages/crypto-kraken-exchange-services/tests/services/yobit/data/balance.ts
  packages/crypto-kraken-exchange-services/tests/services/yobit/data/create-order.ts
  packages/crypto-kraken-exchange-services/tests/services/yobit/data/index.ts
  packages/crypto-kraken-exchange-services/tests/services/yobit/yobit-nonce-factory.spec.ts
  packages/crypto-kraken-exchange-services/tests/services/yobit/yobit-response-parser.spec.ts
  packages/crypto-kraken-exchange-services/tests/services/yobit/yobit-service.spec.ts
Labels: WIP

#110 Fix the YobitUtils' getPairSymbol method (#103)
  packages/crypto-kraken-exchange-services/src/services/yobit/yobit-utils.ts
  packages/crypto-kraken-exchange-services/tests/services/yobit/yobit-utils.spec.ts
Labels: bug

#113 Implement the logic of type checking with concrete fields
  packages/crypto-kraken-core/src/guards.ts
  packages/crypto-kraken-core/tests/guards.spec.ts
Labels: core
